### PR TITLE
fix: Validate manifest CSP properties in v3 format

### LINKED ISSUE #3053: Add support for `isolated_world` alias
See https://github.com/mozilla/addons-linter/pull/3048/files#diff-c24fe98257d3c70153e05cf42301ed84R200

### PR DESCRIPTION
**Pull request by rpl**
Fixes #3053
(also also unblock #3048)

This PR introduce some small changes needed to parse and validate the manifest CSP properties when they are expressed in the new v3 format:

```
  "content_security_policy": {
    "extension_pages": "...",
    "content_scripts": "...",
    // or "isolated_worlds" (which is the chrome compatible alias for the "content_scripts" one)
  }
```

Some other details related to this PR:
- the change is also covered by some additional automated tests.
- the validation messages now also contains the name of the CSP property related
  to the validation message, e.g.

```
Code                              Message                                         Description                                                                                 File                                     Line   Column
MANIFEST_CSP_UNSAFE_EVAL          content_security_policy.extension_pages         In most cases the same result can be achieved differently, therefore it is generally        manifest.json                            
                                  allows 'eval', which has strong security and    prohibited                                                                                                                           
                                  performance implications.
```

### CODE REVIEW

File: tests/unit/parsers/test.manifestjson.js [hunk 1]
```diff
@@ -813,9 +814,46 @@ describe('ManifestJSONParser', () => {
...
+        expect(manifestV3JSONParser.isValid).toEqual(true);
+        const { warnings } = addonLinter.collector;
+
+        const keys = Object.keys(contentSecurityPolicy);
+        for (let i = 0; i < keys.length; i++) {
+          expect(warnings[i].code).toEqual(messages.MANIFEST_CSP);
+          expect(warnings[i].message).toContain(
+            `content_security_policy.${keys[i]}`
+          );
+        }
```
Comment (EnTeQuAk) [inline tests/unit/parsers/test.manifestjson.js]: Unless I'm mistaken we do expect exactly two warnings here, once for `content_scripts` and once for `isolated_worlds` - could we add an assertion for that too?

File: tests/unit/parsers/test.manifestjson.js [hunk 2]
```diff
@@ -874,10 +936,47 @@ describe('ManifestJSONParser', () => {
...
+
+      const manifestV3JSONParser = new ManifestJSONParser(
+        jsonV3,
+        addonLinter.collector
       );
+
+      expect(manifestV3JSONParser.isValid).toEqual(true);
+      const warningsV3 = addonLinter.collector.warnings;
+
+      const keys = Object.keys(contentSecurityPolicy);
```
Comment (EnTeQuAk) [inline tests/unit/parsers/test.manifestjson.js]: Same here, can we add an assertion that makes sure that we have exactly two warnings that match the expected csp warnings?

File: tests/unit/parsers/test.manifestjson.js [hunk 3]
```diff
@@ -874,10 +936,47 @@ describe('ManifestJSONParser', () => {
...
+        // Alias for content_scripts.
+        isolated_world: invalidValue,
+      };
+
+      const jsonV3 = validManifestJSON({
+        content_security_policy: contentSecurityPolicy,
+        applications: {
+          // The new content_security_policy syntax is only supported
+          // on Firefox >= 72.
+          gecko: { strict_min_version: '72.0' },
```
Comment (EnTeQuAk) [inline tests/unit/parsers/test.manifestjson.js]: Do we actually issue a warning / error if `strict_min_version` is `71.0`? I don't think we do as part of the schema, but maybe as part of mdn-browser-compat-data?

**Comment by EnTeQuAk** [comment]
Looks like there's a slight eslint issue - but that's it. https://travis-ci.org/mozilla/addons-linter/jobs/657327008#L1383

File: tests/unit/parsers/test.manifestjson.js (hunk 1 above)
Comment (rpl) [reply tests/unit/parsers/test.manifestjson.js]: No, the linter adds exactly 3 warnings, one for each of those properties ("extension_pages", "content_scripts" and "isolated_worlds").

It is true that `isolated_worlds` is used as an alias for `content_scripts` in Firefox, but that happens in the implementation side, for an API schema perspective they are 2 separate properties of the content_script_policy object.

Nevertheless I can add an assertion for the total number of warning we expect (which is 3 at the moment).

File: tests/unit/parsers/test.manifestjson.js (hunk 3 above)
Comment (rpl) [reply tests/unit/parsers/test.manifestjson.js]: it is coming from the rules implemented based on the metadata coming from `mdn-browser-compat-data`.

File: tests/unit/parsers/test.manifestjson.js (hunk 2 above)
Comment (rpl) [reply tests/unit/parsers/test.manifestjson.js]: As mentioned in the other comment, I can add an assertion to be sure that we got the expected number of warnings (which is 3 for this test)

**Comment by rpl** [comment]
> Looks like there's a slight eslint issue - but that's it. https://travis-ci.org/mozilla/addons-linter/jobs/657327008#L1383

yeah, in the web-ext repo we run the linting checks as part of the `test` npm script and so I didn't run `npm run lint` explicitly and missed to notice that one.

I've pushed the updated version that fixes the linting error (and also added 7c5738f to add the assertion for the expected number of validation warnings).

**Comment by rpl** [comment]
@EnTeQuAk unrelated to this change, I filed #3067 because I noticed that in #3036 I missed to notice that the fake mozilla-central.zip file created in the test case is being created in the project root dir.
