### PR TITLE
Do not warn about nesting css selectors when firefoxStrictMinVersion is >= 117 

### LINKED ISSUE #5102: Allow CSS nesting
### Describe the problem and steps to reproduce it:

Allow CSS nesting as it is supported by Firefox 117+

### What happened?

If i run the linter i get `INVALID_SELECTOR_NESTING` warning

### What did you expect to happen?

that there is no warning about CSS nesting

### Anything else we should know?

https://caniuse.com/css-nesting

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDLINT-370)

### PR DESCRIPTION
**Pull request by schmop**
Fixes #5102

Since Firefox Version 117 CSS selector nesting is supported.
This is not reflected in the `rules/css/invalidNestingSelectors.js` of the addons-linter.
In this changeset I introduced a check against the `firefoxMinStrictVersion`, or `strict_min_version` which is specified in the `manifest.json`.

- [x] This PR relates to an existing open issue and there are no existing PRs open for the same issue.
- [x] Add `Fixes #ISSUENUM` at the top of your PR.
- [x] Add a description of the changes introduced in this PR.
- [x] The change has been successfully run locally.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDLINT-431)

### CODE REVIEW

File: tests/unit/rules/css/test.invalidNesting.js [hunk 1]
```diff
@@ -22,6 +26,23 @@ describe('CSS Rule InvalidNesting', () => {
...
+  it('should not report invalid nesting on sufficient version', async () => {
+    const code = oneLine`/* I'm a comment */
+      #something {
+        .bar {
+          height: 100px;
+        }
+      }`;
+    const cssScanner = new CSSScanner(code, 'fakeFile.css', {
+      addonMetadata: {
+        firefoxMinVersion: '117.0.1',
```
Comment (willdurand) [inline tests/unit/rules/css/test.invalidNesting.js:38]: It'd be good to test with `117` too since you introduced a different comparison function to allow equal values.

File: tests/unit/test.utils.js [hunk 2]
```diff
@@ -602,11 +603,37 @@ describe('basicCompatVersionComparison', () => {
     expect(basicCompatVersionComparison('61', 60)).toBe(true);
   });
 
+  it('should return false when version added is equals than min version', () => {
```
Comment (willdurand) [inline tests/unit/test.utils.js:606]:
```suggestion
  it('should return false when version added is equal to min version', () => {
```

File: tests/unit/test.utils.js [hunk 3]
```diff
@@ -602,11 +603,37 @@ describe('basicCompatVersionComparison', () => {
...
+    expect(basicCompatVersionComparison('61.5.2', 61)).toBe(false);
```
Comment (willdurand) [inline tests/unit/test.utils.js:607]: This makes me think that we have a bug in the current comparison function. I haven't looked in depth yet but I am wondering why we wouldn't allow this..

Comment (willdurand) [reply tests/unit/test.utils.js:607]: I took another look and this `basicCompatVersionComparison` function seems to do the opposite of what I initially thought.

File: src/scanners/base.js [hunk 4]
```diff
@@ -27,6 +27,18 @@ export default class BaseScanner {
...
+   * @property {import('../parsers/manifestjson').Metadata} addonMetadata
+   * @property {import('../collector').default} collector
+   * @property {string[]} disabledRules
+   * @property {string[]} existingFiles
+   * @property {boolean} privileged
+   *
+   * @param {string|Buffer|import('stream').Readable} contents
+   * @param {string} filename
+   * @param {ScannerOptions} options
+   */
```
[the remark this answers is not in the document]
Comment (schmop) [reply src/scanners/base.js:41]: These kind of JSDoc comments are the compromise of having types without using typescript. It helps documenting interfaces, allowing IDEs with code suggestions and helping new devs to faster move around foreign code. I typed parts where I struggled with the given interfaces and needed to dig deeper and documented it right away, so others don't have to. Is this kind of type-documenting style unwelcome in this repository? I can definitely just remove it.

File: src/rules/css/invalidNesting.js [hunk 5]
```diff
@@ -1,10 +1,22 @@
...
+const CSS_NESTING_MIN_VERSION = 117;
+
 export function invalidNesting(
   cssNode,
   filename,
-  { startLine, startColumn } = {}
+  { startLine, startColumn, addonMetadata } = {}
 ) {
+  if (
+    basicCompatVersionComparisonGEQ(
```
[the remark this answers is not in the document]
Comment (schmop) [reply src/rules/css/invalidNesting.js:13]: That might be a bad abbreviation of "Greater or EQual", which is common in TeX, but might not sound familiar in other contexts. I will rename it the function to `isMajorVersionGreaterOrEqual(version, minimalVersion)`, but I am open to suggestions. Naming things is hard.

File: src/parsers/manifestjson.js [hunk 6]
```diff
@@ -47,6 +47,17 @@ import {
...
+/**
+ * @typedef {Object} Metadata
+ * @property {string} id
+ * @property {number} manifestVersion
+ * @property {string} name
+ * @property {number} type
+ * @property {string} version
+ * @property {string} firefoxMinVersion
+ * @property {Set<string>} experimentApiPaths
+ */
```
[the remark this answers is not in the document]
Comment (schmop) [reply src/parsers/manifestjson.js:59]: I moved it down. I added JSDoc, because it helped me a great deal understand what structure I can rely on. I thought it might help future devs aswell, that do not know the internals yet.

File: tests/unit/rules/css/test.invalidNesting.js (hunk 1 above)
Comment (schmop) [reply tests/unit/rules/css/test.invalidNesting.js:38]: I added a test

File: src/rules/css/invalidNesting.js [hunk 7]
```diff
@@ -1,10 +1,22 @@
...
+      addonMetadata?.firefoxMinVersion,
+      CSS_NESTING_MIN_VERSION
```
[the remark this answers is not in the document]
Comment (schmop) [reply src/rules/css/invalidNesting.js:15]: I am pretty sure, the order was intact.
* The first parameter is the configured version as a string (or `undefined` if nothing is configured), that needs to be parsed before we can consume it. It has a form like `"133.2.6"` and the only thing we take a look at is the major-version part `133`.
* The second parameter is the required minimal version, that is hardcoded as a number, like `122`.

Example from the tests:
```js
  it('should return false when version added is undefined', () => {
    expect(basicCompatVersionComparison(undefined, 60)).toBe(false);
  });

  it('should return true when version added is bigger than min version', () => {
    expect(basicCompatVersionComparison('61', 60)).toBe(true);
  });
```
And indeed we can switch! That's great!

File: src/messages/css.js [hunk 8]
```diff
@@ -11,5 +11,7 @@ export const CSS_SYNTAX_ERROR = {
 export const INVALID_SELECTOR_NESTING = {
   code: 'INVALID_SELECTOR_NESTING',
   message: i18n._('Invalid nesting of selectors found'),
-  description: i18n._(`Selectors should not be nested`),
+  description: i18n._(
+    `Selector nesting is supported from firefox version 117.0 and above`
+  ),
```
[the remark this answers is not in the document]
Comment (schmop) [reply src/messages/css.js:16]: Prettier demands this in multiple lines, your formatting will result in a failing pipeline.

File: src/parsers/manifestjson.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (willdurand) [reply src/parsers/manifestjson.js]: I am not against but I think I'd rather see that added in a different PR.

File: src/messages/css.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (willdurand) [reply src/messages/css.js:16]: I tried this suggestion locally and Prettier didn't say anything 🤔

File: src/scanners/base.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (willdurand) [reply src/scanners/base.js:41]: see other comment

File: src/rules/css/invalidNesting.js [hunk 9]
```diff
@@ -1,10 +1,23 @@
...
+  { startLine, startColumn, addonMetadata } = {}
 ) {
+  if (
+    basicCompatVersionComparison(
+      addonMetadata?.firefoxMinVersion,
+      CSS_NESTING_MIN_VERSION
+    )
+  ) {
+    return [];
+  }
```
Comment (willdurand) [inline src/rules/css/invalidNesting.js:20]:
```suggestion
  }
  
```

File: tests/unit/rules/css/test.invalidNesting.js [hunk 10]
```diff
@@ -22,6 +26,40 @@ describe('CSS Rule InvalidNesting', () => {
...
+      }`;
+    const cssScanner = new CSSScanner(code, 'fakeFile.css', {
+      addonMetadata: {
+        firefoxMinVersion: '117.0.0',
+      },
+    });
+
+    const { linterMessages } = await cssScanner.scan();
+    expect(linterMessages.length).toEqual(0);
+  });
```
Comment (willdurand) [inline tests/unit/rules/css/test.invalidNesting.js:61]: It looks like the two test cases are very similar, can we do something like this? cf. https://jestjs.io/docs/api#each

```suggestion
  it.each(["117.0.0", "117.0.1"])('should not report invalid nesting when firefoxMinVersion=%s', async (firefoxMinVersion) => {
    const code = oneLine`/* I'm a comment */
      #something {
        .bar {
          height: 100px;
        }
      }`;
    const cssScanner = new CSSScanner(code, 'fakeFile.css', {
      addonMetadata: {
        firefoxMinVersion,
      },
    });

    const { linterMessages } = await cssScanner.scan();
    expect(linterMessages.length).toEqual(0);
  });
```

**Review by willdurand — CHANGES_REQUESTED** [review]
Thanks.  I requested some more changes but this is looking great.

File: src/rules/css/invalidNesting.js [hunk 11]
```diff
@@ -1,10 +1,24 @@
 import * as messages from 'messages';
 
+import { basicCompatVersionComparison } from '../../utils';
+
+// Allowed version is 117.0 and above
+const CSS_NESTING_MIN_VERSION = 116;
```
Comment (willdurand) [inline src/rules/css/invalidNesting.js:6]: I don't think this is correct, though I understand why you set this constant to `117 - 1`. I think this would work a bit better, though:

```diff
diff --git a/src/rules/css/invalidNesting.js b/src/rules/css/invalidNesting.js
index b8cf9733..b51eab8f 100644
--- a/src/rules/css/invalidNesting.js
+++ b/src/rules/css/invalidNesting.js
@@ -3,7 +3,7 @@ import * as messages from 'messages';
 import { basicCompatVersionComparison } from '../../utils';
 
 // Allowed version is 117.0 and above
-const CSS_NESTING_MIN_VERSION = 116;
+const CSS_NESTING_MIN_VERSION = 117;
 
 export function invalidNesting(
   cssNode,
@@ -11,9 +11,10 @@ export function invalidNesting(
   { startLine, startColumn, addonMetadata } = {}
 ) {
   if (
-    basicCompatVersionComparison(
-      addonMetadata?.firefoxMinVersion,
-      CSS_NESTING_MIN_VERSION
+    addonMetadata?.firefoxMinVersion &&
+    !basicCompatVersionComparison(
+      CSS_NESTING_MIN_VERSION,
+      addonMetadata?.firefoxMinVersion
     )
   ) {
     return [];
diff --git a/tests/unit/rules/css/test.invalidNesting.js b/tests/unit/rules/css/test.invalidNesting.js
index ecf05ea4..4ec67b11 100644
--- a/tests/unit/rules/css/test.invalidNesting.js
+++ b/tests/unit/rules/css/test.invalidNesting.js
@@ -5,28 +5,31 @@ import { VALIDATION_WARNING } from 'const';
 import CSSScanner from 'scanners/css';
 
 describe('CSS Rule InvalidNesting', () => {
-  it('should detect invalid nesting', async () => {
-    const code = oneLine`/* I'm a comment */
+  it.each(['60.5', '116.0', '116'])(
+    'should detect invalid nesting when firefoxMinVersion=%s',
+    async (firefoxMinVersion) => {
+      const code = oneLine`/* I'm a comment */
       #something {
         .bar {
           height: 100px;
         }
       }`;
-    const cssScanner = new CSSScanner(code, 'fakeFile.css', {
-      addonMetadata: {
-        firefoxStrictMinVersion: '60.5',
-      },
-    });
+      const cssScanner = new CSSScanner(code, 'fakeFile.css', {
+        addonMetadata: {
+          firefoxMinVersion,
+        },
+      });
 
-    const { linterMessages } = await cssScanner.scan();
-    expect(linterMessages.length).toEqual(1);
-    expect(linterMessages[0].code).toEqual(
-      messages.INVALID_SELECTOR_NESTING.code
-    );
-    expect(linterMessages[0].type).toEqual(VALIDATION_WARNING);
-  });
+      const { linterMessages } = await cssScanner.scan();
+      expect(linterMessages.length).toEqual(1);
+      expect(linterMessages[0].code).toEqual(
+        messages.INVALID_SELECTOR_NESTING.code
+      );
+      expect(linterMessages[0].type).toEqual(VALIDATION_WARNING);
+    }
+  );
 
-  it.each(['117.0.0', '117.0.1'])(
+  it.each(['117', '117.0', '117.1', '117.0.0', '117.0.1'])(
     'should not report invalid nesting when firefoxMinVersion=%s',
     async (firefoxMinVersion) => {
       const code = oneLine`/* I'm a comment */
```

**Review by willdurand — CHANGES_REQUESTED** [review]

File: src/rules/css/invalidNesting.js (hunk 11 above)
Comment (schmop) [reply src/rules/css/invalidNesting.js]: I applied the changes and added the test cases, where the order of `basicCompatVersionComparison` is relevant and breaks.
The second argument cannot be a string with complex version formats, it will get casted to a `number`. This worked in the special cases of Major versions (`116`) and Major and Minor versions (`116.1`), but not for Major, Minor and Patch Versions.

How do we proceed?

Comment (willdurand) [reply src/rules/css/invalidNesting.js]: Ha. Yeah, now I get it... We should pass `firefoxMinVersion` as second parameter like it is done here: https://github.com/mozilla/addons-linter/blob/0d3e83b8e576dc26b92b369c2debf83697a790d6/src/parsers/manifestjson.js#L158

That said, I overlooked an important detail: `minFirefoxVersion` here is processed here: https://github.com/mozilla/addons-linter/blob/0d3e83b8e576dc26b92b369c2debf83697a790d6/src/parsers/manifestjson.js#682

That's why it doesn't work like it should... What do you think of the following diff?

```diff
diff --git a/src/parsers/manifestjson.js b/src/parsers/manifestjson.js
index b160062b..7b4dae8f 100644
--- a/src/parsers/manifestjson.js
+++ b/src/parsers/manifestjson.js
@@ -1293,6 +1293,7 @@ export default class ManifestJSONParser extends JSONParser {
    * @property {number} type
    * @property {string} version
    * @property {string} firefoxMinVersion
+   * @property {string} firefoxStrictMinVersion
    * @property {Set<string>} experimentApiPaths
    *
    * @returns {Metadata}
@@ -1304,10 +1305,14 @@ export default class ManifestJSONParser extends JSONParser {
       name: this.parsedJSON.name,
       type: PACKAGE_EXTENSION,
       version: this.parsedJSON.version,
+      // This is the `strict_min_version` value set in the `manifest.json` file
+      // for Firefox for desktop.
       firefoxMinVersion:
         this.parsedJSON.applications &&
         this.parsedJSON.applications.gecko &&
         this.parsedJSON.applications.gecko.strict_min_version,
+      // This is the strict min *major* version for Firefox for desktop.
+      firefoxStrictMinVersion: firefoxStrictMinVersion(this.parsedJSON),
       experimentApiPaths: this.getExperimentApiPaths(),
     };
   }
diff --git a/src/rules/css/invalidNesting.js b/src/rules/css/invalidNesting.js
index b8cf9733..cd6d22de 100644
--- a/src/rules/css/invalidNesting.js
+++ b/src/rules/css/invalidNesting.js
@@ -3,7 +3,7 @@ import * as messages from 'messages';
 import { basicCompatVersionComparison } from '../../utils';
 
 // Allowed version is 117.0 and above
-const CSS_NESTING_MIN_VERSION = 116;
+const CSS_NESTING_MIN_VERSION = 117;
 
 export function invalidNesting(
   cssNode,
@@ -11,9 +11,10 @@ export function invalidNesting(
   { startLine, startColumn, addonMetadata } = {}
 ) {
   if (
-    basicCompatVersionComparison(
-      addonMetadata?.firefoxMinVersion,
-      CSS_NESTING_MIN_VERSION
+    addonMetadata?.firefoxStrictMinVersion &&
+    !basicCompatVersionComparison(
+      CSS_NESTING_MIN_VERSION,
+      addonMetadata?.firefoxStrictMinVersion
     )
   ) {
     return [];
diff --git a/tests/unit/rules/css/test.invalidNesting.js b/tests/unit/rules/css/test.invalidNesting.js
index ecf05ea4..2ad372f4 100644
--- a/tests/unit/rules/css/test.invalidNesting.js
+++ b/tests/unit/rules/css/test.invalidNesting.js
@@ -5,30 +5,33 @@ import { VALIDATION_WARNING } from 'const';
 import CSSScanner from 'scanners/css';
 
 describe('CSS Rule InvalidNesting', () => {
-  it('should detect invalid nesting', async () => {
-    const code = oneLine`/* I'm a comment */
+  it.each([60, 116])(
+    'should detect invalid nesting when firefoxStrictMinVersion=%d',
+    async (firefoxStrictMinVersion) => {
+      const code = oneLine`/* I'm a comment */
       #something {
         .bar {
           height: 100px;
         }
       }`;
-    const cssScanner = new CSSScanner(code, 'fakeFile.css', {
-      addonMetadata: {
-        firefoxStrictMinVersion: '60.5',
-      },
-    });
+      const cssScanner = new CSSScanner(code, 'fakeFile.css', {
+        addonMetadata: {
+          firefoxStrictMinVersion,
+        },
+      });
 
-    const { linterMessages } = await cssScanner.scan();
-    expect(linterMessages.length).toEqual(1);
-    expect(linterMessages[0].code).toEqual(
-      messages.INVALID_SELECTOR_NESTING.code
-    );
-    expect(linterMessages[0].type).toEqual(VALIDATION_WARNING);
-  });
+      const { linterMessages } = await cssScanner.scan();
+      expect(linterMessages.length).toEqual(1);
+      expect(linterMessages[0].code).toEqual(
+        messages.INVALID_SELECTOR_NESTING.code
+      );
+      expect(linterMessages[0].type).toEqual(VALIDATION_WARNING);
+    }
+  );
 
-  it.each(['117.0.0', '117.0.1'])(
-    'should not report invalid nesting when firefoxMinVersion=%s',
-    async (firefoxMinVersion) => {
+  it.each([117, 118])(
+    'should not report invalid nesting when firefoxStrictMinVersion=%d',
+    async (firefoxStrictMinVersion) => {
       const code = oneLine`/* I'm a comment */
       #something {
         .bar {
@@ -37,7 +40,7 @@ describe('CSS Rule InvalidNesting', () => {
       }`;
       const cssScanner = new CSSScanner(code, 'fakeFile.css', {
         addonMetadata: {
-          firefoxMinVersion,
+          firefoxStrictMinVersion,
         },
       });
       const { linterMessages } = await cssScanner.scan();
```

Comment (schmop) [reply src/rules/css/invalidNesting.js]: Oh, I didn't know, there already was a function to extract the major version! Sweet!

**Review by willdurand — APPROVED** [review]
Excellent, thanks!
