### PR TITLE
fix: Prevent mv3 permissions errors to be wrongly reported in mv2 addon validation

### LINKED ISSUE #4367: Host permissions regarded as invalid in `permissions` if other invalid permissions are present
### Describe the problem and steps to reproduce it:

Load an extension with the following manifest file:
```
{
  "manifest_version": 2,
  "version": "25.8.0",
  "name": "Example",
  "permissions": [
    "SOME_INVALID_PERMISSION",
    "https://www.example.com/"
  ]
}
```

### What happened?

`https://www.example.com/` is seen as an invalid permission. 

### What did you expect to happen?

`https://www.example.com/` should be seen as valid.

### Anything else we should know?

This only happens if `SOME_INVALID_PERMISSION` is present.

### LINKED ISSUE #4521: Possible typo in src/schema/validator.js (mix_manifest_version)
https://github.com/mozilla/addons-linter/blob/300ad70f9caf8cee628778af2c5d28e2302167e1/src/schema/validator.js#L90

Should that be `max_manifest_version`?

### PR DESCRIPTION
**Pull request by rpl**
Fixes #4367
(also fixes #4521, including the fix for the typo in `isRelevantError` helper function and additional test coverage added to test.schema.js to cover the fixed typo with an explicit test case).  

The unexpected validation warning reported for a valid host permission (filed as addons-linter issue #4367)
seems to be due to the fact that both manifest_version 2 and manifest_version 3 definitions for the
permissions manifest field are being processed.

The current implementation is trying to make sure to filter out the errors not relevant for the current
add-on based on the error.parentSchema property (See isRelevantError helper function defined in
src/schema/validator.js).

Unfortunately this approach is unable to filter out all irrelevant errors, in particular for JSONSchema
types that are referenced in a min/max_manifest_version conditioned entry with more then 1 level deep nesting,
the error.parentSchema will not be the one explicitly including the min/max_manifest_version property and
this is what makes the error triggered by the min_manifest_version 3 version of the "permissions" to be
wrongly reported as part of a manifest_version 2 add-on validation.

This patch is currently filtering the schema data at "JSONSchema data compile"-time and omitting from the
schema data all entries with min/max_manifest_version that do not match the minimum and maximum manifest_version
set per schema validator config or if they don't apply to the actual add-on manifest_version.

NOTE: Ideally a better (and less expesive at runtime) approach may be to this kind of JSONSchema data filtering
at import time (by creating a different set of JSONSchema data per manifest_version).

### CODE REVIEW

File: src/schema/validator.js [hunk 1]
```diff
@@ -409,9 +412,47 @@ export class SchemaValidator {
...
+    };
+
+    // Omit from the schema data all entries that includes a
+    // min/max_manifest_version which is outside of the minimum
+    // and maximum manifest_version currently allowed per validator
+    // config and if they do not apply to the addon manifest_version.
+    //
+    const schemaObject = JSON.parse(
+      JSON.stringify(this.schemaObject, replacer, 2)
+    );
```
Comment (rpl) [inline src/schema/validator.js:453]: @willdurand this is currently traversing the JSONSchema data by using JSON.stringify, which is likely not the best way to traverse the json objects given that it is stringifying all data and then parsing it again, I used it mainly as a quick way to give the approach a try and confirm if that would be a possible way to avoid these unexpected errors.

Besides the JSON.stringify trick, as I also mentioned in the PR description comment a better (and less expesive at runtime) approach may be to this kind of JSONSchema data filtering at import time (by creating a different set of JSONSchema data per manifest_version).

We may also consider looking into that approach now and see if we can get an alternative patch without a too big of an effort.

Let me know wdyt.

(in the PR description I tried to explain in a bit more detail what is going on in practice, but I'm happy to have a chat if that description didn't yet help you to get a good picture of the underlying issue).

**Comment by willdurand** [comment]
> Let's touch base about this points in the next few days, e.g. after you got a chance to take a look to this version.

Yeah, that's actually something I forgot to let you know earlier today.. I read this new patch and your comments/concerns. We should discuss some time next week!

**Comment by willdurand** [comment]
As per our last discussion, the idea was to:

1. move these changes to a new PR with a different goal: we eventually want to simplify the JSON schema in the linter so that will be a first step (having two sets of schema for mv2 and mv3). Later, we'll merge all files to have a JSON file per manifest version. After that we'll try to simplify the structure of the JSON schema
2. switch back to the old patch (with the replacer function) to fix https://github.com/mozilla/addons-linter/issues/4367. The unproven fear was that it would impact the perfs negatively but we came to the conclusion that this was unproven and rather unlikely

**Comment by willdurand** [comment]
> [...] Later, we'll merge all files to have a JSON file per manifest version [...]

I filed #4511 for that, let's file issues for:

> [...] we eventually want to simplify the JSON schema in the linter so that will be a first step (having two sets of schema for mv2 and mv3) [...]

and

> [...]  After that we'll try to simplify the structure of the JSON schema [...]

**Comment by willdurand** [comment]
I filed https://github.com/mozilla/addons-linter/issues/4512 and https://github.com/mozilla/addons-linter/issues/4513

**Comment by rpl** [comment]
@willdurand I have restored the initial version of this PR as we agreed on, then added the test case introduced along with the other approach to provide explicit test coverage around the issue this is meant to fix.

**Comment by willdurand** [comment]
> (also fixes #4523, including the fix for the typo in `isRelevantError` helper function and additional test coverage added to test.schema.js to cover the fixed typo with an explicit test case).

That fixes https://github.com/mozilla/addons-linter/issues/4521, not the PR.

**Comment by rpl** [comment]
> > (also fixes #4523, including the fix for the typo in `isRelevantError` helper function and additional test coverage added to test.schema.js to cover the fixed typo with an explicit test case).
> 
> That fixes #4521, not the PR.

right, reference to the right issue number fixed in the PR description.

File: src/schema/validator.js [hunk 2]
```diff
@@ -409,9 +412,55 @@ export class SchemaValidator {
...
+          }
+
+          return includeItem;
+        });
+        return patchedValue;
+      }
+      return value;
+    };
+
+    // Omit from the manifest schema data all entries that includes a
```
Comment (willdurand) [inline src/schema/validator.js:447]:
```suggestion
    // Omit from the manifest schema data all entries that include a
```

File: src/schema/validator.js [hunk 3]
```diff
@@ -518,6 +567,12 @@ export class SchemaValidator {
         }
 
         if (!res) {
+          // If the addon manifest is out of an enum values min/max manifest version range,
+          // don't report an additional validation error for the mix/max_manifest_version
```
Comment (willdurand) [inline src/schema/validator.js:571]:
```suggestion
          // don't report an additional validation error for the min/max_manifest_version
```

File: tests/unit/parsers/test.manifestjson.js [hunk 4]
```diff
@@ -528,6 +528,89 @@ describe('ManifestJSONParser', () => {
...
+          }),
+        ])
+      );
+      expect(manifestJSONParser.isValid).toEqual(false);
+
+      // Confirm that the unexpected origin is reported as a validation
+      // error if the extension is a manifest version 3 extension.
+      const jsonv3 = validManifestJSON({
+        manifest_version: 3,
+        applications: {
```
Comment (willdurand) [inline tests/unit/parsers/test.manifestjson.js:573]:
```suggestion
        browser_specific_settings: {
```

File: tests/unit/schema/test.schema.js [hunk 5]
```diff
@@ -146,33 +200,138 @@ describe('Schema JSON', () => {
...
+          expect.objectContaining({
+            instancePath: '/browser_action/popup',
+            keyword: 'type',
+            message: 'must be string',
+          }),
+        ])
+      );
 
-      expect(validator.validateAddon.errors).toEqual(
+      // Errors for values in the fantary_api enum restricted to MV1 and MV3 should not be reported.
```
Comment (willdurand) [inline tests/unit/schema/test.schema.js:229]:
```suggestion
      // Errors for values in the fantasy_api enum restricted to MV1 and MV3 should not be reported.
```

File: tests/unit/schema/test.schema.js [hunk 6]
```diff
@@ -146,33 +200,138 @@ describe('Schema JSON', () => {
...
+      );
+      expect(validateAddon.errors).toEqual(
+        expect.not.arrayContaining([
+          expect.objectContaining({
+            instancePath: '/fantasy_api/fantasy_key_obsolete',
+          }),
+        ])
+      );
+
+      // Errors for values in the fantary_api enum supported by MV2 should be reported.
```
Comment (willdurand) [inline tests/unit/schema/test.schema.js:256]:
```suggestion
      // Errors for values in the fantasy_api enum supported by MV2 should be reported.
```

File: tests/unit/schema/test.schema.js [hunk 7]
```diff
@@ -146,33 +200,138 @@ describe('Schema JSON', () => {
...
+        expect.not.arrayContaining([
+          expect.objectContaining({
+            instancePath: '/browser_action/popup',
+            keyword: 'type',
+            message: 'must be string',
+          }),
+        ])
+      );
+
+      // Errors for values in the fantary_api enum restricted to MV1 and MV2 should not be reported.
```
Comment (willdurand) [inline tests/unit/schema/test.schema.js:297]:
```suggestion
      // Errors for values in the fantasy_api enum restricted to MV1 and MV2 should not be reported.
```

File: tests/unit/schema/test.schema.js [hunk 8]
```diff
@@ -146,33 +200,138 @@ describe('Schema JSON', () => {
...
+      );
+      expect(validateAddon.errors).toEqual(
+        expect.not.arrayContaining([
+          expect.objectContaining({
+            instancePath: '/fantasy_api/fantasy_key_obsolete',
+          }),
+        ])
+      );
+
+      // Errors for values in the fantary_api enum supported by MV3 should be reported.
```
Comment (willdurand) [inline tests/unit/schema/test.schema.js:324]:
```suggestion
      // Errors for values in the fantasy_api enum supported by MV3 should be reported.
```

**Review by willdurand — CHANGES_REQUESTED** [review]
Looking good, a few questions and typos.

File: src/schema/validator.js [hunk 9]
```diff
@@ -163,7 +166,7 @@ function getManifestVersionsRange(validatorOptions) {
     );
   }
 
-  return { minimum, maximum };
+  return { minimum, maximum, addon };
```
[the remark this answers is not in the document]
Comment (rpl) [reply src/schema/validator.js]: I renamed it to currentAddon (just to make it clear it is the version of the current addon being validated, and not a current manifest version option set on the linter, like minimum and maximum are).

Let me know if that is a reasonable name from this property also from your perspective.

**Comment by rpl** [comment]
@willdurand I've just updated this PR based on your last round of review comments (https://github.com/mozilla/addons-linter/pull/4397/commits/a14d5017569935f2d6f52251109091f2e5f6b052), this should be ready for a final review pass.

File: src/schema/validator.js (hunk 9 above)
[the remark this answers is not in the document]
Comment (willdurand) [reply src/schema/validator.js]: Ok so that's my fault actually. I should have suggested something else: I don't like that we return the addon manifest version in something called "range". This is no longer a range anymore since it has more than min/max.

I tried to move the logic for `currentAddon` where it is actually used and the test suite still passes:

```diff
diff --git a/src/schema/validator.js b/src/schema/validator.js
index 6c700742..57f0ef25 100644
--- a/src/schema/validator.js
+++ b/src/schema/validator.js
@@ -140,8 +140,7 @@ function filterErrors(
 }
 
 function getManifestVersionsRange(validatorOptions) {
-  const { minManifestVersion, maxManifestVersion, addonManifestVersion } =
-    validatorOptions;
+  const { minManifestVersion, maxManifestVersion } = validatorOptions;
 
   const minimum =
     minManifestVersion == null
@@ -164,10 +163,7 @@ function getManifestVersionsRange(validatorOptions) {
     );
   }
 
-  const currentAddon =
-    addonManifestVersion == null ? minimum : addonManifestVersion;
-
-  return { minimum, maximum, currentAddon };
+  return { minimum, maximum };
 }
 
 export class SchemaValidator {
@@ -413,8 +409,11 @@ export class SchemaValidator {
   }
 
   _compileAddonValidator(validator) {
-    const { minimum, currentAddon, maximum } =
-      this.allowedManifestVersionsRange;
+    const { minimum, maximum } = this.allowedManifestVersionsRange;
+    const { addonManifestVersion } = this._options;
+
+    const manifestVersion =
+      addonManifestVersion == null ? minimum : addonManifestVersion;
 
     const replacer = (key, value) => {
       if (Array.isArray(value)) {
@@ -427,7 +426,7 @@ export class SchemaValidator {
             includeItem =
               item.min_manifest_version >= minimum &&
               item.min_manifest_version <= maximum &&
-              item.min_manifest_version <= currentAddon;
+              item.min_manifest_version <= manifestVersion;
           }
           if (
             item?.max_manifest_version &&
@@ -436,7 +435,7 @@ export class SchemaValidator {
             includeItem =
               item.max_manifest_version >= minimum &&
               item.max_manifest_version <= maximum &&
-              item.max_manifest_version >= currentAddon;
+              item.max_manifest_version >= manifestVersion;
           }
 
           return includeItem;
```

WDYT?

[the remark this answers is not in the document]
Comment (rpl) [reply src/schema/validator.js]: @willdurand ah, now I see what you meant, I applied your diff and made some more small tweaks on top of it (basically moved it into a Validator class getter, see https://github.com/mozilla/addons-linter/pull/4397/commits/3c2a0a7c72e0d92f29da3c110b9e05f5f64a77f9), how that looks to you?

**Review by willdurand — APPROVED** [review]
