### PR TITLE
fix: Accept top level await

### LINKED ISSUE #4020: Syntax error with a top-level await and no import
### Describe the problem and steps to reproduce it:

Files with a _top-level await_ and no _import_: returns a syntax error.

```JavaScript
await browser.storage.local.get();
```

### What happened?

```
Validation Summary:

errors          1              
notices         0              
warnings        0              

ERRORS:

Code              Message        Description               File          Line   Column
JS_SYNTAX_ERROR   JavaScript     There is a JavaScript     testcase.js   1      7     
                  syntax error   syntax error in your                                
                   (Parsing as   code, which might be                                
                  script         related to some                                     
                  error:         experimental JavaScript                             
                  Unexpected     features that aren't an                             
                  token          official part of the                                
                  browser at     language specification                              
                  line: 1 and    and therefore not                                   
                  column: 7)     supported yet. The                                  
                                 validation cannot                                   
                                 continue on this file.
```

### What did you expect to happen?

No error reported.

### Anything else we should know?

I have no error with ESLint.

### PR DESCRIPTION
**Pull request by regseb**
Fixes #4020

In the detection of the type of a JavaScript file, if the file contains an `await` in the top level: consider that it's a module.

### CODE REVIEW

File: src/scanners/javascript.js [hunk 1]
```diff
@@ -218,10 +218,20 @@ export default class JavaScriptScanner {
...
+      'FunctionDeclaration',
+      'FunctionExpression',
+    ];
 
     if (possibleImportExportTypes.includes(node.type)) {
       return 'module';
     }
+    if (topLevel && node.type === 'AwaitExpression') {
+      return 'module';
+    }
```
Comment (willdurand) [inline src/scanners/javascript.js:232]: nit: could we merge both `if` blocks?

**Review by willdurand — CHANGES_REQUESTED** [review]
This looks _fine_. I have a nit then we can probably merge this PR. Thanks!

**Review by willdurand — APPROVED** [review]
