### PR TITLE
fix(themes): Log validation errors on theme manifests using the deprecated LWT aliases

### LINKED ISSUE #2463: Turn MANIFEST_THEME_LWT_ALIAS into a linting error once support for these aliases is removed in Firefox
### Describe the problem and steps to reproduce it:

As a follow up for #2259, once the support for these LWT theme aliases is going to be removed from Firefox, we should turn the `MANIFEST_THEME_LWT_ALIAS` (which is being added as part of #2283) from a linting warning to a linting error.

Based on https://bugzilla.mozilla.org/show_bug.cgi?id=1472740#c10, the linter should start to mark this as a linting error when Firefox 69 reached the beta channel.

### PR DESCRIPTION
**Pull request by rpl**
This PR fixes #2463, follow up for #2259 (which started to log validation warning for these deprecated LWT aliases).

This is also related to [Bug 1472740](https://bugzilla.mozilla.org/show_bug.cgi?id=1472740), which tracks the changes on the Firefox side.

Some notes about this change:

- `toolbar_text` is not deprecated anymore (See [Bug 1472740 Comment 24](https://bugzilla.mozilla.org/show_bug.cgi?id=1472740#c24) for a rationale)
- The LWT aliases properties will be ignored on Firefox (starting from Firefox >= 70 if the patch is not going to be uplifted to 69), as it happens for any other unknown theme manifest property
- [The patch attached to Bug 1472740 ([D37891])](https://phabricator.services.mozilla.com/D37891) is going to update the deprecation message included in the schema to mention explicitly that the deprecated properties are being ignored (but it will not prevent the installation, as it also happens for any other unknown theme manifest property)

### CODE REVIEW

**Comment by rpl** [comment]
added @wagnerand as an additional reviewer, to also have an opinion from an "add-on review" point of view.

File: tests/unit/parsers/test.manifestjson.js [hunk 1]
```diff
@@ -2358,34 +2361,30 @@ describe('ManifestJSONParser', () => {
 
         expect(manifestJSONParser.isValid).toBeFalsy();
 
-        expect(errors).toEqual([]);
+        expect(warnings).toEqual([]);
 
-        const actualWarnings = warnings.map((warn) => {
+        const actualErrors = errors.map((warn) => {
```
Comment (wagnerand) [inline tests/unit/parsers/test.manifestjson.js]: Nit: Could rename `warn` as well?

Comment (rpl) [reply tests/unit/parsers/test.manifestjson.js]: he, yeah, I missed that one :-)
