### PR TITLE
fix: Report a warning on manifest_version 3 extensions targeting Firefox for Android

### LINKED ISSUE #5104: Report a warning on manifest_version 3 targeting Firefox for Android
### Describe the problem and steps to reproduce it:

Manifest Version 3 support on Firefox for Android is currently limited compared to Firefox Desktop (as an example: on Firefox for Android there isn't currently any visual indication that would be highlighting to the user that an extension is currently pending on the user granting the host_permissions specified in the manifest before being able to access the currently active tab)

### What happened?

We are not providing to the developers that may be targeting Firefox for Android any pointers related to the limitations they may be hitting when the extension being submitted is a manifest_version 3 extension.

### What did you expect to happen?

We should be highlight to the user the limitations they would need to be aware of through a new linting warning, the linting warning should provide a link to a documentation page that can be provide a more detailed description of the limitation and how the developer may deal with (than how much we could fit into the linting warning description).

### TODO list

- [ ] draft a patch to implement the new warning
- [ ] coordinate with @dotproto to detemine where the rule description should point the extension developer to get a more detailed description and guidance about the Fenix MV3 limitations they should be aware of

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDLINT-372)

### PR DESCRIPTION
**Pull request by rpl**
Fixes #5104

## TODO List

- [x] replace the placeholder for the shortened url to a more detailed doc page with a real moz.la link (moved to separate followup: #5110)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDLINT-373)

### CODE REVIEW

File: src/messages/manifestjson.js [hunk 1]
```diff
@@ -23,6 +23,15 @@ export const MANIFEST_FIELD_INVALID = {
...
 };
 
+export const MANIFEST_V3_FIREFOX_ANDROID_LIMITATIONS = {
+  code: 'MANIFEST_V3_FIREFOX_ANDROID_LIMITATIONS',
+  message: i18n._(
+    'Firefox for Android Manifest Version 3 is currently limited.'
+  ),
+  description: i18n._('See https://mzl.la/TODO for more information.'),
+  file: MANIFEST_JSON,
+};
```
Comment (rpl) [inline src/messages/manifestjson.js:33]: @willdurand I opted for a new rule code with the following rationale:
- the rule code would be specific to mv3 limitations on Firefox for Android
- the rule code would potentially apply to other mv3 limitation other than the one specifically related to the host_permissions and the badge highlighting on Desktop when the extension is pending on the user granting those permissions
- included  "FIREFOX_ANDROID" spelled explicitly in the new rule code because we do have at least one existing rule code including that already

Let me know if we do want to tweak the rule code (or the name or description) to use a different convention and text.

@dotproto to complete this PR we would need to agreed on where to point the shortened url to be included in the final version of this patch, the amount of details we can fit into the rule message or description is pretty limited and would not allow us to provide that much guidance (and the warning by itself is unlikely to be really useful without a doc page where we may direct the developers to get more details about the limitations they will need to consider), would you mind to help me with that part?

File: docs/rules.md [hunk 2]
```diff
@@ -141,6 +141,7 @@ Rules are sorted by severity.
 | `APPLICATIONS_INVALID`                                  | error    | The `applications` property is no longer accepted in Manifest Version 3 and above.                                                                                                 |
 | `VERSION_FORMAT_DEPRECATED`                             | warning  | The version string should be simplified.                                                                                                                                           |
 | `VERSION_FORMAT_INVALID`                                | error    | The version string is not valid because its format is too complex.                                                                                                                 |
+| `MANIFEST_V3_FIREFOX_ANDROID_LIMITATIONS`               | warning  | The extension is marked compatible with a Firefox for Android version with a limited Manifest Version 3 support                                                                    |
```
Comment (willdurand) [inline docs/rules.md:144]:
```suggestion
| `MANIFEST_V3_FIREFOX_ANDROID_LIMITATIONS`               | warning  | The extension is marked as compatible with a Firefox for Android version that doesn't fully support Manifest Version 3                                                                    |
```

maybe?

File: src/messages/manifestjson.js [hunk 3]
```diff
@@ -23,6 +23,13 @@ export const MANIFEST_FIELD_INVALID = {
   file: MANIFEST_JSON,
 };
 
+export const MANIFEST_V3_FIREFOX_ANDROID_LIMITATIONS = {
+  code: 'MANIFEST_V3_FIREFOX_ANDROID_LIMITATIONS',
+  message: i18n._('Limited Manifest Version 3 support on Firefox for Android.'),
```
Comment (willdurand) [inline src/messages/manifestjson.js:28]:
```suggestion
  message: i18n._('Manifest Version 3 isn't fully supported on Firefox for Android yet.'),
```

**Review by willdurand — COMMENTED** [review]
Looks good to me overall.

File: docs/rules.md (hunk 2 above)
Comment (rpl) [reply docs/rules.md]: :+1:  looks like it reads better, updated

**Comment by rpl** [comment]
@willdurand as we agreed earlier today, I've filed a separate followup to add the shorted link in the description of the new warning (tracked by #5110), then updated this PR accordingly. This should be ready for your final review pass.

**Review by willdurand — APPROVED** [review]

File: src/messages/manifestjson.js (hunk 1 above)
Comment (rpl) [reply src/messages/manifestjson.js]: Link to additional docs moved to the separate followup tracked by #5110
