### PR TITLE
warn on deprecated apis

### LINKED ISSUE #761: Deprecated chrome.extension.onRequest API
**Steps to reproduce:**
Submit the attached web-extension on AMO-dev: 
[grammar_ginger.zip](https://github.com/mozilla/addons-linter/files/325587/grammar_ginger.zip)

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-20) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console: TypeError: chrome.extension.onRequest is undefined
[Learn More]background.min.js:21:89382
- More details in: https://developer.chrome.com/extensions/extension#event-onRequest

### LINKED ISSUE #762: Deprecated chrome.app.getDetails API
**Steps to reproduce:**
Submit the attached web-extension on AMO-dev:
[weather.zip](https://github.com/mozilla/addons-linter/files/325639/weather.zip)

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-20) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console: TypeError: chrome.app is undefined
[Learn More]network.js:9:1
- More details in: http://stackoverflow.com/questions/9167150/where-is-chrome-app-officially-documented and https://bugs.chromium.org/p/chromium/issues/detail?id=111354

### LINKED ISSUE #769: Deprecated chrome.tabs.getSelected API
**Steps to reproduce:**
Submit the attached webextension:
[test11.zip](https://github.com/mozilla/addons-linter/files/328240/test11.zip)

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-22) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console while clicking on the webextension icon: TypeError: chrome.tabs.getSelected is not a function         [Learn More]popup.js:15:3
- More details in: https://developer.chrome.com/extensions/tabs#method-getSelected

### LINKED ISSUE #772: Deprecated chrome.tabs.sendRequest API
**Steps to reproduce:**
Submit the attached web-extension on AMO-dev:
[imagequilts.zip](https://github.com/mozilla/addons-linter/files/329948/imagequilts.zip)

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-22) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console while clicking on the webextension icon: chrome.tabs.sendRequest is not a function     background.js:59
- More details in: https://developer.chrome.com/extensions/tabs#method-sendRequest

### LINKED ISSUE #773: Deprecated chrome.tabs.getAllInWindow API
**Steps to reproduce:**
Submit the attached web-extension:
[chrome_clock.zip](https://github.com/mozilla/addons-linter/files/329969/chrome_clock.zip)

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-22) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console while clicking on the webextension icon: chrome.tabs.getAllInWindow is not a function     popup.js:16
- More details in: https://developer.chrome.com/extensions/tabs#method-getAllInWindow

### LINKED ISSUE #774: Deprecated chrome.tabs.onSelectionChanged API
**Steps to reproduce:**
Submit the attached web-extension:
[be_limitless.zip](https://github.com/mozilla/addons-linter/files/330075/be_limitless.zip)

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-22) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console: TypeError: chrome.tabs.onSelectionChanged is undefined
[Learn More]background.js:215:3
- More details in: https://developer.chrome.com/extensions/tabs#event-onSelectionChanged

### LINKED ISSUE #775: Deprecated chrome.tabs.onActiveChanged API
**Steps to reproduce:**
Submit the attached web-extension:
[ghostery.zip](https://github.com/mozilla/addons-linter/files/330114/ghostery.zip)

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-22) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console: TypeError: chrome.tabs.onActiveChanged is undefined
[Learn More]background.js:15590:3
- More details in: https://developer.chrome.com/extensions/tabs#event-onActiveChanged

### LINKED ISSUE #776: Deprecated chrome.extension.sendRequest  API
**Steps to reproduce:**
Submit the attached web-extension:
[gamingwonderland.zip](https://github.com/mozilla/addons-linter/files/330198/gamingwonderland.zip)

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-23) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console: TypeError: chrome.extension.sendRequest is not a function  messaging.js:113
- More details in: https://developer.chrome.com/extensions/extension#method-sendRequest

### LINKED ISSUE #777: Deprecated chrome.extension.onRequestExternal API
**Steps to reproduce:**
Submit the attached web-extension:

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-23) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console: TypeError: chrome.extension.onRequestExternal is undefined [Learn More] openPopoutWhenAsked.js:2:1
- More details in: https://developer.chrome.com/extensions/extension#event-onRequestExternal

### PR DESCRIPTION
**Pull request by andymckay**
* supports: #780 and maybe fixes it, dunno
* fixes #777
* fixes #776
* fixes #775
* fixes #774
* fixes #773
* fixes #772
* fixes #769
* fixes #762
* fixes #761

* feels a bit clunky in that the code needs to be truncated down and each deprecated API needs to be added in 3 places
* also not sure about the eslint scanner, `node.object.object.name` feels clunky

### CODE REVIEW

**Comment by andymckay** [comment]
...also I think that's a record (for me) of most bug resolved in one pull request.

**Comment by tofumatt** [comment]
Damn! That's a lot of bugs! 👍

File: src/const.js [hunk 1]
```diff
@@ -130,9 +131,20 @@ export const FLAGGED_FILE_MAGIC_NUMBERS = [
...
+
+export const DEPRECATED_APIS = [
+  'app.getDetails',
+  'extension.onRequestExternal',
+  'tabs.getAllInWindow',
+  'tabs.getSelected',
+  'tabs.onActiveChanged',
+  'tabs.onSelectionChanged',
+  'tabs.sendRequest',
+  'extension.onRequest',
```
Comment (tofumatt) [inline src/const.js]: This is some OCD, but could we alphabetise these? Makes it easier to scan.

File: src/messages/javascript.js [hunk 2]
```diff
@@ -239,3 +239,30 @@ export const KNOWN_LIBRARY = {
...
+
+export const TABS_GETSELECTED = deprecatedAPI('tabs.getSelected');
+export const TABS_SENDREQUEST = deprecatedAPI('tabs.sendRequest');
+export const TABS_GETALLINWINDOW = deprecatedAPI('tabs.getAllInWindow');
+export const TABS_ONSELECTIONCHANGED = deprecatedAPI(
+  'tabs.onSelectionChanged');
+export const TABS_ONACTIVECHANGED = deprecatedAPI('tabs.onActiveChanged');
+export const EXTENSION_SENDREQUEST = deprecatedAPI('extension.sendRequest');
+// Sadly we'll have to concat this one to fit under 26 chars.
+export const EXTENSION_ONREQUESTEXTERN = deprecatedAPI(
```
Comment (tofumatt) [inline src/messages/javascript.js]: I would concat the group (`EXT` over `EXTENSION`) rather than the specific message. eg `EXT_ONREQUESTETERNAL`

File: src/messages/javascript.js [hunk 3]
```diff
@@ -239,3 +239,30 @@ export const KNOWN_LIBRARY = {
...
+function deprecatedAPI(api) {
+  return {
+    code: apiToMessage(api),
+    legacyCode: [
+      'js',
+      'deprecated',
+      api,
+    ],
+    message: _(`"${api}" is deprecated or unimplemented`),
+    description: _(singleLineString`APIs that have been deprecated by Chrome
```
Comment (tofumatt) [inline src/messages/javascript.js]: I would change this to `This API has been deprecated by Chrome and has not been implemented by Firefox`. That is more in line with other descriptions.

File: tests/scanners/test.javascript.js [hunk 4]
```diff
@@ -282,4 +281,18 @@ describe('JavaScript Scanner', function() {
                      Object.keys(ignorePrivateFunctions(rules)).length);
       });
   });
+
+  for (let api of DEPRECATED_APIS) {
+    it(`should return warn when ${api} is used`, () => {
```
Comment (tofumatt) [inline tests/scanners/test.javascript.js]: Nitpick but "warning" instead of "warn" would be clearer.

**Comment by tofumatt** [comment]
r+wc

I like the way you did this! Just lots of little nitpicks but cool overall.

**Comment by vasilicamihasca** [comment]
Tested using all the webextensions attached in bugs, but there is no warning displayed while submitting a webextension which uses a deprecated api.

@andymckay any thoughts about this?

**Comment by andymckay** [comment]
The linter hasn't been tagged and deployed to add-ons dev yet. This normally happens around the push time.

**Comment by tofumatt** [comment]
Literally doing it right now :-)

**Comment by andymckay** [comment]
@vasilicamihasca this is on stage now, here's one i tested:

screenshot 2016-07-27 15 46 01

**Comment by vasilicamihasca** [comment]
Verified fixed on AMO-dev, AMO-stage and AMO-production using Firefox 51.0a1 (2016-08-31) under Windows 10 64-bit. There are warnings displayed at webextension submission for each deprecated/unimplemented api.

File: src/rules/javascript/webextension_api.js [hunk 5]
```diff
@@ -0,0 +1,16 @@
+import { DEPRECATED_APIS } from 'const';
+import { apiToMessage } from '../../utils';
+
+export function webextension_api(context) {
+  return {
+    MemberExpression: function(node) {
+      if (node.object.object &&
```
Comment (muffinresearch) [inline src/rules/javascript/webextension_api.js]: You could be more defensive here if `node.object` is undefined this will blow up.
