### PR TITLE
fail if both install.rdf and manifest.json defined

### LINKED ISSUE #605: Raise an error if there's another metadata-file if manifest.json exists
We should throw an exception if there's a `install.rdf` or `package.json` once there's a `manifest.json` to make sure we block duplicated metadata early enough.

Tracking: https://github.com/mozilla/addons-server/issues/2450

### PR DESCRIPTION
**Pull request by andymckay**
* fixes #605 sorta

before:
screenshot 2016-04-20 15 03 56

after:
screenshot 2016-04-20 15 05 14

It feels like i'm changing some fundamental decision about the linter was written that if it just fails with some key files it throws a system error. I felt that this way there's a clear and consistent error @EnTeQuAk can pass back to the user who uploaded an addon. But I'm probably wrong :)

### CODE REVIEW

File: src/messages/layout.js [hunk 1]
```diff
@@ -47,6 +47,19 @@ export const TYPE_NO_MANIFEST_JSON = {
     will be attempted to be inferred by package layout.`),
 };
 
+export const TYPE_MULTIPLE_FILES = {
```
Comment (muffinresearch) [inline src/messages/layout.js]: I think this might be better as `MULTIPLE_MANIFEST_FILES` or `MULTIPLE_MANIFESTS`

File: src/messages/layout.js [hunk 2]
```diff
@@ -47,6 +47,19 @@ export const TYPE_NO_MANIFEST_JSON = {
...
+  code: 'TYPE_MULTIPLE_FILES',
+  legacyCode: [
+    'typedetection',
+    'detect_type',
+    'install_rdf_andy_manifest_json',
```
Comment (muffinresearch) [inline src/messages/layout.js]: Typo: install_rdf_**andy**_manifest_json

File: src/messages/layout.js (hunk 1 above)
Comment (muffinresearch) [inline src/messages/layout.js]: That said if this matches the previous validator I guess we might be better to keep it like this for easier comparisons.

File: src/messages/layout.js (hunk 2 above)
Comment (andymckay) [inline src/messages/layout.js]: hehe

File: src/messages/layout.js (hunk 1 above)
Comment (andymckay) [inline src/messages/layout.js]: There wasn't anything in the previous validator about this, so I'm easy.

**Comment by muffinresearch** [comment]
r+wc
